---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  namespace: fio-test
spec:
  containers:
   - name: performance
     image: quay.io/ocsci/perf:latest
     imagePullPolicy: IfNotPresent
     command: ['/bin/sh']
     stdin: true
     tty: true
     volumeMounts:
       - name: mypvc
         mountPath: /mnt
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: pvc-test
       readOnly: false